sudo: false
language: ruby
cache: bundler
bundler_args: --retry=3 --jobs=3
rvm:
    - 2.2.1
    - ruby-head
    - jruby
    - jruby-head
matrix:
    allow_failures:
    - rvm: jruby
    - rvm: jruby-head
    fast_finish: true
    
before_script:
  - psql -c 'create database mezzo_test;' -U postgres
  - psql -c 'create database mezzo_development;' -U postgres
  - psql -c 'create database mezzo_production;' -U postgres
  
notifications:
  slack: teamgigs:Nnem2T8oYDBaz6Sww5bDkhgH